kind = "mobile"
previewPath = "/"
title = "Dieta AI"
version = "1.0.0"
id = "artifacts/dieta-ai"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/" ]
localPort = 21790

[services.development]
run = "pnpm --filter @workspace/dieta-ai run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/dieta-ai", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/dieta-ai", "run", "serve" ]

[services.env]
PORT = "21790"
BASE_PATH = "/"
