const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#3D7A1E",
    background: "#F5F8F2",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#2C5F1A",
    primaryForeground: "#FFFFFF",
    secondary: "#EBF3E4",
    secondaryForeground: "#2C5F1A",
    muted: "#EBF3E4",
    mutedForeground: "#6B7F60",
    accent: "#5BA82E",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#D4E6C3",
    input: "#E8F2E0",
    success: "#4CAF50",
    chartGreen: "#3D7A1E",
    chartRed: "#E53935",
  },
  dark: {
    text: "#E6EFE1",
    tint: "#6FBF4A",
    background: "#0E130E",
    foreground: "#E6EFE1",
    card: "#182018",
    cardForeground: "#E6EFE1",
    primary: "#4E9F35",
    primaryForeground: "#FFFFFF",
    secondary: "#1E2A1C",
    secondaryForeground: "#A5D88A",
    muted: "#1E2A1C",
    mutedForeground: "#95A58D",
    accent: "#6FBF4A",
    accentForeground: "#0E130E",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#2A3828",
    input: "#1F2A1E",
    success: "#4CAF50",
    chartGreen: "#6FBF4A",
    chartRed: "#F87171",
  },
  radius: 16,
};

export default colors;
